//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InGodWeTrust.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InGodWeTrust.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Ботаны.
        /// </summary>
        internal static string Botans {
            get {
                return ResourceManager.GetString("Botans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Извините, сегодня воскресение. Сотворить людей не получится!.
        /// </summary>
        internal static string CheckDateMessage {
            get {
                return ResourceManager.GetString("CheckDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Крутые предки.
        /// </summary>
        internal static string CoolParents {
            get {
                return ResourceManager.GetString("CoolParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ж.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте. Вы используете консоль бога. Сколько людей вы хотите сотворить?.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели некорректное число. Попробуйте еще раз.
        /// </summary>
        internal static string IncorrectNumberMessage {
            get {
                return ResourceManager.GetString("IncorrectNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на М.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ович.
        /// </summary>
        internal static string ManPatronymicEndRes {
            get {
                return ResourceManager.GetString("ManPatronymicEndRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алексей.
        /// </summary>
        internal static string NameAlex {
            get {
                return ResourceManager.GetString("NameAlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артём.
        /// </summary>
        internal static string NameArtyom {
            get {
                return ResourceManager.GetString("NameArtyom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Константин.
        /// </summary>
        internal static string NameConstantin {
            get {
                return ResourceManager.GetString("NameConstantin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Екатерина.
        /// </summary>
        internal static string NameEkaterina {
            get {
                return ResourceManager.GetString("NameEkaterina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иван.
        /// </summary>
        internal static string NameIvan {
            get {
                return ResourceManager.GetString("NameIvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любовь.
        /// </summary>
        internal static string NameLubov {
            get {
                return ResourceManager.GetString("NameLubov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Семён.
        /// </summary>
        internal static string NameSemyon {
            get {
                return ResourceManager.GetString("NameSemyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлана.
        /// </summary>
        internal static string NameSvetlana {
            get {
                return ResourceManager.GetString("NameSvetlana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Татьяна.
        /// </summary>
        internal static string NameTatiana {
            get {
                return ResourceManager.GetString("NameTatiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валентина.
        /// </summary>
        internal static string NameValentina {
            get {
                return ResourceManager.GetString("NameValentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виктория.
        /// </summary>
        internal static string NameVictoria {
            get {
                return ResourceManager.GetString("NameVictoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владимир.
        /// </summary>
        internal static string NameVladimir {
            get {
                return ResourceManager.GetString("NameVladimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычные родители.
        /// </summary>
        internal static string Parents {
            get {
                return ResourceManager.GetString("Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Возраст: .
        /// </summary>
        internal static string PreAge {
            get {
                return ResourceManager.GetString("PreAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Средняя оценка: .
        /// </summary>
        internal static string PreAverageRating {
            get {
                return ResourceManager.GetString("PreAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Количество детей: .
        /// </summary>
        internal static string PreKidsAmount {
            get {
                return ResourceManager.GetString("PreKidsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Количество денег: .
        /// </summary>
        internal static string PreMoneyAmount {
            get {
                return ResourceManager.GetString("PreMoneyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя: .
        /// </summary>
        internal static string PreName {
            get {
                return ResourceManager.GetString("PreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Отчество: .
        /// </summary>
        internal static string PrePatronimic {
            get {
                return ResourceManager.GetString("PrePatronimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на , Пол: .
        /// </summary>
        internal static string PreSex {
            get {
                return ResourceManager.GetString("PreSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Студенты.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма всех денег крутых предков выведены в файл TotalMoney.txt (рядом с исполняемым файлом).
        /// </summary>
        internal static string TotalMoneyFile {
            get {
                return ResourceManager.GetString("TotalMoneyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на овна.
        /// </summary>
        internal static string WomanPatronymicEndRes {
            get {
                return ResourceManager.GetString("WomanPatronymicEndRes", resourceCulture);
            }
        }
    }
}
