//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionImpossible.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionImpossible.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энн Хэтэуэй.
        /// </summary>
        internal static string ActorAHathaway {
            get {
                return ResourceManager.GetString("ActorAHathaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брэд Питт.
        /// </summary>
        internal static string ActorBPitt {
            get {
                return ResourceManager.GetString("ActorBPitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кристиан Бэйл.
        /// </summary>
        internal static string ActorCBale {
            get {
                return ResourceManager.GetString("ActorCBale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Константин Хабенский.
        /// </summary>
        internal static string ActorCHabenskiy {
            get {
                return ResourceManager.GetString("ActorCHabenskiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эдвард Нортон.
        /// </summary>
        internal static string ActorENorton {
            get {
                return ResourceManager.GetString("ActorENorton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франсуа Клюзе.
        /// </summary>
        internal static string ActorFCluzet {
            get {
                return ResourceManager.GetString("ActorFCluzet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хелена Бонем Картер.
        /// </summary>
        internal static string ActorHBCarter {
            get {
                return ResourceManager.GetString("ActorHBCarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Джим Керри.
        /// </summary>
        internal static string ActorJCarrey {
            get {
                return ResourceManager.GetString("ActorJCarrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Джоди Фостер.
        /// </summary>
        internal static string ActorJFoster {
            get {
                return ResourceManager.GetString("ActorJFoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Киану Ривз.
        /// </summary>
        internal static string ActorKReeves {
            get {
                return ResourceManager.GetString("ActorKReeves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курт Уиммер.
        /// </summary>
        internal static string ActorKWimmer {
            get {
                return ResourceManager.GetString("ActorKWimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лоренс Фишбёрн.
        /// </summary>
        internal static string ActorLFishburne {
            get {
                return ResourceManager.GetString("ActorLFishburne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Майкл Дуглас.
        /// </summary>
        internal static string ActorMDouglas {
            get {
                return ResourceManager.GetString("ActorMDouglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мэттью МакКонахи.
        /// </summary>
        internal static string ActorMMcConaughey {
            get {
                return ResourceManager.GetString("ActorMMcConaughey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Омар Си.
        /// </summary>
        internal static string ActorOSy {
            get {
                return ResourceManager.GetString("ActorOSy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter movie actors.
        /// </summary>
        internal static string ActorsToolTip {
            get {
                return ResourceManager.GetString("ActorsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тэй Диггз.
        /// </summary>
        internal static string ActorTDiggs {
            get {
                return ResourceManager.GetString("ActorTDiggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уилл Смит.
        /// </summary>
        internal static string ActorWSmith {
            get {
                return ResourceManager.GetString("ActorWSmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актёр.
        /// </summary>
        internal static string AttributeActor {
            get {
                return ResourceManager.GetString("AttributeActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        internal static string AttributeCountry {
            get {
                return ResourceManager.GetString("AttributeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режиссер.
        /// </summary>
        internal static string AttributeDirector {
            get {
                return ResourceManager.GetString("AttributeDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string AttributeName {
            get {
                return ResourceManager.GetString("AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постер.
        /// </summary>
        internal static string AttributePoster {
            get {
                return ResourceManager.GetString("AttributePoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год.
        /// </summary>
        internal static string AttributeYear {
            get {
                return ResourceManager.GetString("AttributeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Франция.
        /// </summary>
        internal static string CountryFrance {
            get {
                return ResourceManager.GetString("CountryFrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия.
        /// </summary>
        internal static string CountryRussia {
            get {
                return ResourceManager.GetString("CountryRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter movie country.
        /// </summary>
        internal static string CountryToolTip {
            get {
                return ResourceManager.GetString("CountryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Великобритания.
        /// </summary>
        internal static string CountryUnitedKingdom {
            get {
                return ResourceManager.GetString("CountryUnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на США.
        /// </summary>
        internal static string CountryUSA {
            get {
                return ResourceManager.GetString("CountryUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultMovieImage {
            get {
                object obj = ResourceManager.GetObject("DefaultMovieImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алексей Красовский.
        /// </summary>
        internal static string DirectorAKrasovskiy {
            get {
                return ResourceManager.GetString("DirectorAKrasovskiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кристофер Нолан.
        /// </summary>
        internal static string DirectorCNolan {
            get {
                return ResourceManager.GetString("DirectorCNolan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дэвид Финчер.
        /// </summary>
        internal static string DirectorDFincher {
            get {
                return ResourceManager.GetString("DirectorDFincher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Френсис Лоуренс.
        /// </summary>
        internal static string DirectorFLawrence {
            get {
                return ResourceManager.GetString("DirectorFLawrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курт Уиммер.
        /// </summary>
        internal static string DirectorKWimmer {
            get {
                return ResourceManager.GetString("DirectorKWimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лана Вачовски.
        /// </summary>
        internal static string DirectorLWachowski {
            get {
                return ResourceManager.GetString("DirectorLWachowski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оливье Накаш.
        /// </summary>
        internal static string DirectorONakache {
            get {
                return ResourceManager.GetString("DirectorONakache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роберт Земекис.
        /// </summary>
        internal static string DirectorRZemeckis {
            get {
                return ResourceManager.GetString("DirectorRZemeckis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter movie director.
        /// </summary>
        internal static string DirectorToolTip {
            get {
                return ResourceManager.GetString("DirectorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Том Шэдьяк.
        /// </summary>
        internal static string DirectorTShadyac {
            get {
                return ResourceManager.GetString("DirectorTShadyac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        internal static string DownloadInProcess {
            get {
                return ResourceManager.GetString("DownloadInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field contains invalid characters.
        /// </summary>
        internal static string ErrorInvalidCharacters {
            get {
                return ResourceManager.GetString("ErrorInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title is incorrect.
        /// </summary>
        internal static string ErrorTitleIsIncorrect {
            get {
                return ResourceManager.GetString("ErrorTitleIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year is incorrect.
        /// </summary>
        internal static string ErrorYearIsIncorrect {
            get {
                return ResourceManager.GetString("ErrorYearIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите выйти?.
        /// </summary>
        internal static string ExitPrompt {
            get {
                return ResourceManager.GetString("ExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bruce.jpg.
        /// </summary>
        internal static string ImgPathBruce {
            get {
                return ResourceManager.GetString("ImgPathBruce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collector.jpg.
        /// </summary>
        internal static string ImgPathCollector {
            get {
                return ResourceManager.GetString("ImgPathCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constantine.jpg.
        /// </summary>
        internal static string ImgPathConstantine {
            get {
                return ResourceManager.GetString("ImgPathConstantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equilibrium.jpg.
        /// </summary>
        internal static string ImgPathEquilibrium {
            get {
                return ResourceManager.GetString("ImgPathEquilibrium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FightClub.jpg.
        /// </summary>
        internal static string ImgPathFightClub {
            get {
                return ResourceManager.GetString("ImgPathFightClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IAmLegend.jpg.
        /// </summary>
        internal static string ImgPathIAmLegend {
            get {
                return ResourceManager.GetString("ImgPathIAmLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interstellar.jpg.
        /// </summary>
        internal static string ImgPathInterstellar {
            get {
                return ResourceManager.GetString("ImgPathInterstellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intouchables.jpg.
        /// </summary>
        internal static string ImgPathIntouchables {
            get {
                return ResourceManager.GetString("ImgPathIntouchables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matrix.jpg.
        /// </summary>
        internal static string ImgPathMatrix {
            get {
                return ResourceManager.GetString("ImgPathMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TheGame.jpg.
        /// </summary>
        internal static string ImgPathTheGame {
            get {
                return ResourceManager.GetString("ImgPathTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле заполнено некорректно.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брюс Всемогущий.
        /// </summary>
        internal static string MovieBruceAlmighty {
            get {
                return ResourceManager.GetString("MovieBruceAlmighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллектор.
        /// </summary>
        internal static string MovieCollector {
            get {
                return ResourceManager.GetString("MovieCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Константин.
        /// </summary>
        internal static string MovieConstantine {
            get {
                return ResourceManager.GetString("MovieConstantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакт.
        /// </summary>
        internal static string MovieContact {
            get {
                return ResourceManager.GetString("MovieContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить фильм &quot;{0}&quot;?.
        /// </summary>
        internal static string MovieDeletePrompt {
            get {
                return ResourceManager.GetString("MovieDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эквилибриум.
        /// </summary>
        internal static string MovieEquilibrium {
            get {
                return ResourceManager.GetString("MovieEquilibrium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бойцовский клуб.
        /// </summary>
        internal static string MovieFightClub {
            get {
                return ResourceManager.GetString("MovieFightClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра.
        /// </summary>
        internal static string MovieGame {
            get {
                return ResourceManager.GetString("MovieGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я – легенда.
        /// </summary>
        internal static string MovieIAmLegend {
            get {
                return ResourceManager.GetString("MovieIAmLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интерстеллар.
        /// </summary>
        internal static string MovieInterstellar {
            get {
                return ResourceManager.GetString("MovieInterstellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неприкасаемые.
        /// </summary>
        internal static string MovieIntouchables {
            get {
                return ResourceManager.GetString("MovieIntouchables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матрица.
        /// </summary>
        internal static string MovieMatrix {
            get {
                return ResourceManager.GetString("MovieMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter movie name.
        /// </summary>
        internal static string NameToolTip {
            get {
                return ResourceManager.GetString("NameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter movie year.
        /// </summary>
        internal static string YearToolTip {
            get {
                return ResourceManager.GetString("YearToolTip", resourceCulture);
            }
        }
    }
}
