//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multithreading.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multithreading.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ура! Экзамен окончен..
        /// </summary>
        internal static string ExamFinished {
            get {
                return ResourceManager.GetString("ExamFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получили оценки.
        /// </summary>
        internal static string GotGrade {
            get {
                return ResourceManager.GetString("GotGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Андрей.
        /// </summary>
        internal static string MenNameAndrey {
            get {
                return ResourceManager.GetString("MenNameAndrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Григорий.
        /// </summary>
        internal static string MenNameGrisha {
            get {
                return ResourceManager.GetString("MenNameGrisha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Константин.
        /// </summary>
        internal static string MenNameKostia {
            get {
                return ResourceManager.GetString("MenNameKostia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анатолий.
        /// </summary>
        internal static string MenNameTolia {
            get {
                return ResourceManager.GetString("MenNameTolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Василий.
        /// </summary>
        internal static string MenNameVasia {
            get {
                return ResourceManager.GetString("MenNameVasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Венеамин.
        /// </summary>
        internal static string MenNameVenya {
            get {
                return ResourceManager.GetString("MenNameVenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экзамен по многопоточию.
        /// </summary>
        internal static string MnogopotochieExam {
            get {
                return ResourceManager.GetString("MnogopotochieExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процесс сдачи экзамена.
        /// </summary>
        internal static string ProgressHelpMessage {
            get {
                return ResourceManager.GetString("ProgressHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экзамен в процессе.
        /// </summary>
        internal static string StartButtonExamInProgress {
            get {
                return ResourceManager.GetString("StartButtonExamInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать экзамен.
        /// </summary>
        internal static string StartButtonStartExam {
            get {
                return ResourceManager.GetString("StartButtonStartExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать экзамен.
        /// </summary>
        internal static string StartExam {
            get {
                return ResourceManager.GetString("StartExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать следующий экзамен.
        /// </summary>
        internal static string StartNextExam {
            get {
                return ResourceManager.GetString("StartNextExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Зачётки.
        /// </summary>
        internal static string StudentGradebookNumber {
            get {
                return ResourceManager.GetString("StudentGradebookNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cтудент.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на студентов..
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груздев.
        /// </summary>
        internal static string SurnameGrusdev {
            get {
                return ResourceManager.GetString("SurnameGrusdev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метёлкин.
        /// </summary>
        internal static string SurnameMetiolkin {
            get {
                return ResourceManager.GetString("SurnameMetiolkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Милонов.
        /// </summary>
        internal static string SurnameMilonov {
            get {
                return ResourceManager.GetString("SurnameMilonov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Молчанов.
        /// </summary>
        internal static string SurnameMolchanov {
            get {
                return ResourceManager.GetString("SurnameMolchanov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Третьяков.
        /// </summary>
        internal static string SurnameTretiakov {
            get {
                return ResourceManager.GetString("SurnameTretiakov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Екатерина.
        /// </summary>
        internal static string WomanNameKatia {
            get {
                return ResourceManager.GetString("WomanNameKatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любовь.
        /// </summary>
        internal static string WomanNameLuba {
            get {
                return ResourceManager.GetString("WomanNameLuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мирослава.
        /// </summary>
        internal static string WomanNameMiroslava {
            get {
                return ResourceManager.GetString("WomanNameMiroslava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлана.
        /// </summary>
        internal static string WomanNameSveta {
            get {
                return ResourceManager.GetString("WomanNameSveta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валентина.
        /// </summary>
        internal static string WomanNameValia {
            get {
                return ResourceManager.GetString("WomanNameValia", resourceCulture);
            }
        }
    }
}
